# frozen_string_literal: true

require "thor"

module Ares
end

require_relative "cli/cli"
require_relative "orchestrator/task"
require_relative "orchestrator/planner"
require_relative "orchestrator/executor"
require_relative "agents/claude_agent"
require_relative "agents/codex_agent"
require_relative "agents/gemini_agent"
require_relative "agents/cursor_agent"
require_relative "orchestrator/router"
require_relative "orchestrator/reducer"
require_relative "orchestrator/token_governor"
require_relative "task_graph/graph"
require_relative "task_graph/node"
require_relative "task_graph/scheduler"
require_relative "task_graph/executor_pool"
require_relative "task_graph/parallel_scheduler"
require_relative "context/repo_scanner"
require_relative "context/ast_extractor"
require_relative "context/symbol_graph"
require_relative "context/context_builder"
require_relative "context/code_index"
require_relative "context/task_cache"
require_relative "context/memory_store"
require_relative "context/diff_context"
require_relative "context_engine/repo_scanner"
require_relative "context_engine/ast_extractor"
require_relative "context_engine/symbol_graph"
require_relative "context_engine/dependency_graph"
require_relative "context_engine/file_summarizer"
require_relative "context_engine/context_compressor"
require_relative "context_engine/pipeline"
require_relative "local_ai/ollama_client"
require_relative "local_ai/summarizer"
require_relative "local_ai/task_classifier"
require_relative "local_ai/diff_summarizer"
require_relative "local_ai/memory_summarizer"
require_relative "local_ai/guardrail_validator"
require_relative "local_ai/context_compressor"
require_relative "self_improve/repo_analyzer"
require_relative "self_improve/improvement_detector"
require_relative "self_improve/improvement_planner"
require_relative "self_improve/patch_generator"
require_relative "self_improve/patch_validator"
require_relative "self_improve/improvement_store"
require_relative "self_improve/test_runner"
require_relative "self_improve/evaluator"
require_relative "self_improve/loop"
